[package]
name = "gpio"
version = "0.1.0"
edition = "2024"

[dependencies]
gpio-cdev = { version = "0.6.0", features = ["async-tokio"]}
tokio = {version = "*", features = ["rt-multi-thread", "macros"]}
futures = "*"
